### ISSUE TITLE
Better menu for more entries

### ISSUE THREAD

**Issue by reinefjord** [teknologkoren/flasquelistan#18]
A js popup (dropup?) or something like that when pressing the "more" button in the navbar. Use the js to catch clicks on the link and do a popup instead of page reload. This way, things will work perfectly even if you turn off js, use a browser without js-support or if the js breaks for some reason (aka. [progressive enhancement](https://en.wikipedia.org/wiki/Progressive_enhancement), which is what flasquelistan is all about :) )

If we wanna be fancy about it, put the 'more' links in a dict in a jinja snippet that both the more "page" and the more "popup" can import. As the navbar is always visible (except for on the login page), it could be imported to layout.html and added as a display: none \<ul> in the misc \<li>.

**Comment by Alge** [comment]
Should we close this since there's currently 2 menues/nav bars?

**Comment by reinefjord** [comment]
I don't think they are mutually exclusive. We could still add a javascript button somewhere that's easier to reach while removing the menu to gain some vertical space, but it doesn't feel too necessary with the new menu. We can reopen this in the future if we feel like it after using the new menu for a while.
