### ISSUE TITLE
Warning for no transaction shows even when transactions are available

### ISSUE THREAD

**Issue by Alge** [teknologkoren/flasquelistan#19]
<img width="590" alt="Screenshot 2019-05-17 at 13 44 13" src="https://user-images.githubusercontent.com/7383768/57925875-fcf17700-78a9-11e9-8a07-78eb710d0cf9.png">

**Comment by reinefjord** [comment]
af0944ab151a999ddf44753fe96dfa0806ec78b0 is the culprit. I removed `.hidden` because I didn't think it was related to anything else than the emma-popup.
