### ISSUE TITLE
change profile picture form behaves wierdly when scrolling

### ISSUE THREAD

**Issue by Alge** [teknologkoren/flasquelistan#31]
When scrolling in this form the title is moved up out of view from this:
<img width="424" alt="Screenshot 2019-05-18 at 18 21 31" src="https://user-images.githubusercontent.com/7383768/57972392-e32f5d00-7999-11e9-9130-b123f10ff61c.png">

To this:

<img width="393" alt="Screenshot 2019-05-18 at 18 21 37" src="https://user-images.githubusercontent.com/7383768/57972393-e4f92080-7999-11e9-8273-cc9832fd0ea9.png">

The title (and the top line) should stay visible on top and items should be limited to inside the box

**Comment by reinefjord** [comment]
oof. chrome can't render shit properly.
