### ISSUE TITLE
Possibility to migrate from old django database without password resets

### ISSUE THREAD

**Issue by Alge** [teknologkoren/flasquelistan#37]
Requiers checks of 2 different password hashes as the flasquelistan uses another hashing algorithm

**Comment by reinefjord** [comment]
Werkzeug has a [check_password_hash()](https://werkzeug.palletsprojects.com/en/0.15.x/utils/#werkzeug.security.check_password_hash) that support pbkdf2 that Strequelistan uses. Werkzeug is used by flask and thus available without more dependencies, though specifying it as a dep explicitly might be a good idea.

**Comment by reinefjord** [comment]
fixed with 81f5e3f56ce67467551b2cfbeeada3a8a8f00dd0
