### ISSUE TITLE
[Firefox - Windows] No video is shown when clicking one of the product buttons

### ISSUE THREAD

**Issue by Alge** [teknologkoren/flasquelistan#49]
The video of emma stone isn't shown in firefox on windows without downloading a Media Feature Pack from microsoft [https://support.mozilla.org/sv/kb/fix-video-audio-problems-firefox-windows?as=u&utm_source=inproduct](https://support.mozilla.org/sv/kb/fix-video-audio-problems-firefox-windows?as=u&utm_source=inproduct)
![Capture](https://user-images.githubusercontent.com/7383768/60536160-f6a64580-9d05-11e9-93b2-47e6227fe2d4.PNG)

**Comment by reinefjord** [comment]
oh ffs. I removed the webm source because firefox didn't want to play the video first time after load, but mp4 worked. i guess windows doesn't come with a mp4 decoder by default? I'm pretty sure the webm-thing with firefox is a bug in firefox, I couldn't find any workarounds for it.

**Comment by reinefjord** [comment]
only a problem in Windows N that is missing relevant media decoders. Wont fix.
