### ISSUE TITLE
 Möjlighet att ändra andras profilbilder på andras profiler

### ISSUE THREAD

**Issue by Alge** [teknologkoren/flasquelistan#6]

**Comment by reinefjord** [comment]
Tycker att det bör vara utformat så att andra användare bara kan ladda upp profilbild som sätts automatiskt, blir för "enkelt" om man kan välja bland gamla profilbilder. Att bara ladda upp uppmuntrar också mer till uppladdning av nya bilder.

**Comment by Alge** [comment]
Håller med
