### ISSUE TITLE
Automatically focusing login email field can be done with html 5 attribute instead of JS

### ISSUE THREAD

**Issue by reinefjord** [teknologkoren/flasquelistan#62]
The [autofocus attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#autofocus) does the exact same thing as the JS does, but without JS :)

Supported in all browsers that are not Safari on iOS because why would Safari on iOS do anything right? I mean, it's only supported since Firefox 4, Chrome 5, IE 10, Android (Browser) 3, and Safari on OS X 5. It also works in iOS WebViews. But not Safari.

**Comment by Alge** [comment]
So if it doesn't work on safari we shouldn't remove the JS version untill they get their stuff fixes...

**Comment by reinefjord** [comment]
Apparently, it was never implemented because it was deemed annoying to have the keyboard pop up automatically. This doesn't happen on Firefox for Android, nor Chrome on Android, and I bet it doesn't happen on Safari for iOS. Having the feature on mobile thus serves no purpose, while on desktop, where autofocus works everywhere, it does.
