### ISSUE TITLE
Möjlighet för admins att sätta lösenord på användares konton

### ISSUE THREAD

**Issue by Alge** [teknologkoren/flasquelistan#7]
Just nu behöver man veta deras lösenord

**Comment by reinefjord** [comment]
Behövs det verkligen? Om admin sätter ett lösenord bör användaren byta direkt efter ändå, kan väl lika gärna be användaren att begära ett nytt via /reset då. Däremot skulle det vara praktiskt att kunna byta e-postadress vilket också kräver användarens lösenord atm så enklast är nog bara att låta admins ändra båda fälten utan lösenord. Kanske faktiskt kräva admins eget lösenord istället för att förhindra andra personer från att ändra om man låter ett adminkonto vara inloggat på en delad dator. Skulle dock lösas automatiskt av #4.

**Comment by Alge** [comment]
Är rätt ofta jag låter användare skriva in ett eget lösenord när jag är
inloggad, är även bra att ha som fail-safe om mailåterställningen skulle
sluta fungera
