### ISSUE TITLE
Returning streque-pay transactions doesn't return both of the transaction objects

### ISSUE THREAD

**Issue by Alge** [teknologkoren/flasquelistan#71]
if Alice sends 1kr to Bob, and a admin return the transaction created for Alice, she gets her 1kr back, and bob still has his 1 kr Alice sent him.

**Comment by reinefjord** [comment]
`CreditTransfer`-objektet har en `void()` som returnerar båda: https://github.com/teknologkoren/flasquelistan/blob/4730fdda8ada7e4dd106f4ce79fd75219fda6e8a/flasquelistan/models.py#L487-L489

Vi borde visa upp (endast) avsändarens transaktion och ändra så att ångra-knappen kör `CreditTransfer.void()` istället.
