### ISSUE TITLE
Filter by group / jump to group

### ISSUE THREAD

**Issue by grensjo** [teknologkoren/flasquelistan#89]
It would be really helpful with a group of buttons or a dropdown below the filter field to quickly filter by group. When you're on mobile and want to streque for a bass or PQ member, you either need to scroll a lot, or fumble with your on-screen keyboard to find the person. A group filter would make this process painless, simple and quick, regardless of your current emoji.

Alternatively, the button could instead just take you down to that group (could be implemented with bookmarks). In that case we would also need a "jump to top" button/link below each group.

**Comment by reinefjord** [comment]
> regardless of your current emoji

See also #2 for improvements to the current filter.
